# -*- coding: utf-8 -*-
"""final_trial_#67: Automated IMPRO Implants detection using object detection

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vyDkNLNaq5Vi7rK4ehsDH6eKOvkDAO46
"""

# Change Runtime Type to GPU, before connecting | Author: Abhijay Rajvansh | LinkedIn: https://in.linkedin.com/in/abhijayrajvansh

from google.colab import drive

drive.mount("/content/gdrive")

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/gdrive/MyDrive

# Creating Directories and Cloning Official YOLOv7 Github repository

# Commented out IPython magic to ensure Python compatibility.
import os

if not os.path.isdir("trial-67"):
  os.makedirs("trial-67")

# %cd "trial-67"

# YOLOv7 Updated unofficial git repository by Abhijay Rajvansh

!git clone https://github.com/WongKinYiu/yolov7.git

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/gdrive/MyDrive/trial-67/yolov7

# Commented out IPython magic to ensure Python compatibility.
# %pip install -r requirements.txt

# Adding YOLOv7 weights#yolov7 weights
!wget https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7.pt

!pip install --upgrade torch==1.11.0 torchvision==0.12.0

# RuntimeError: CUDA out of memory. Tried to allocate 100.00 MiB
import torch
print(torch.__version__)
# torch.cuda.empty_cache()

# Commented out IPython magic to ensure Python compatibility.
# %pwd

# Commented out IPython magic to ensure Python compatibility.
# %ls

#training_started # Biomet Taperloc
!python train.py --workers 1 --device 0 --batch-size 8 --epochs 200 --img 640 640 --data data/custom-data.yaml --hyp data/hyp.scratch.custom.yaml --cfg cfg/training/custom-yolov7.yaml --weights yolov7.pt --name yolov7-custom

#testing Biomet Taperloc
!python detect.py --weights runs/train/yolov7-custom6/weights/best.pt --conf 0.5 --img-size 640 --source biomet-taperloc130.jpg --no-trace
# 97 percent accuracy

!python detect.py --weights runs/train/yolov7-custom6/weights/best.pt --conf 0.5 --img-size 640 --source biomet-taperloc1.jpeg --no-trace

